### ISSUE TITLE
[SDK-Swift] Account and Account migration related issues

### ISSUE THREAD

**Issue by vienlt** [bitmark-inc/bitmark-sdk-swift#15]
- [x] ~There isn't an account migration interface as described in the [sdk-doc](https://sdk-docs.bitmark.com/?swift#account-migration)~

- [x] bitmarks are not transferred after executing `Migration.rekey` 

- [x] It is currently allowing users to parse an account of another network (expect an error returned  instead).

**Comment by anhnguyenbitmark** [comment]
> There isn't an account migration interface as described in the sdk-doc

@vienlt `Migrate()` is obsolete.

**Comment by vienlt** [comment]
@anhnguyenbitmark : Moved the first items to sdk-doc.
