### ISSUE TITLE
[SDK-Swift] Asset registration - set fingerprint using directly the file URL doesn't work

### ISSUE THREAD

**Issue by vienlt** [bitmark-inc/bitmark-sdk-swift#16]

**Comment by anhnguyenbitmark** [comment]
It works. See: https://github.com/bitmark-inc/bitmark-sdk-swift/blob/master/Sample/swift-sdk-sample/swift-sdk-sample/SDK-Samples/AssetRegistrationSample.swift#L17

**Comment by vienlt** [comment]
Close as it isn't a bug.
